version: '3.7'
networks:
  elastic:
    name: elastic
    driver: bridge
  repository:
    name: repository
    driver: bridge
services:
  apm-server:
    container_name: apm-server
    depends_on:
      - elasticsearch
      - kibana
    environment:
      ELASTIC_SEARCH_HOSTS: http://elasticsearch:9200
    image: docker.elastic.co/apm/apm-server:7.6.0
    networks:
      - elastic
    ports:
      - 8200:8200
      - 8201:8201
    user: apm-server
    volumes:
      - ./elastic/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.6.0
    environment:
      ELASTIC_SEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - 5601:5601
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - repository
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
